spring:
    data:
        cassandra:
            contact-points: localhost
            port: 9042
            cluster-name: datacenter1
            keyspace-name: main
            schema-action: NONE

cassandra:
    migration:
        keyspace-name: main